services:
  ehei_store_store:
    class: Ehei\StoreBundle\Service\Store
    public: false

  Ehei\StoreBundle\Service\Store: '@ehei_store_store'

  Ehei\StoreBundle\Controller\:
    resource: '../../Controller/'
    tags: ['controller.service_arguments']
